language: python
python:
  - '3.6'

sudo: false

cache: pip

before_install:
  - pip install -U pip

install: 'pip install codecov -r requirements.txt -r requirements-dev.txt'

before_script: 'python manage.py compilemessages'

script:
  # Run the tests
  - flake8
  - isort -c
  - pytest -ra -vvv --cov=.
  # Check requirements.txt
  - |
    if [ "$TRAVIS_PYTHON_VERSION" = "3.6" ]; then
        pip install -q pip==18.0
        pip install -q prequ==1.4.3
        prequ check -v
    fi

addons:
  postgresql: '9.6'
  apt:
    packages:
    - libxmlsec1-dev
    - pkg-config

after_success: codecov
